jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      id: spotless_check
      name: Check code style with Spotless
      run: ./gradlew spotlessCheck
    - continue-on-error: true
      name: Execute Gradle build
      run: ./gradlew build
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: VirusTotal scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        files: './build/libs/*.jar

          '
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
