jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Check JSON syntax
      uses: limitusus/json-syntax-check@v2
      with:
        pattern: \.json$
name: JSON syntax
on:
  repository_dispatch:
    types: trigger-ga___jsonsyntax.yml
