jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@main
      with:
        days-before-close: 7
        days-before-stale: 60
        enable-statistics: true
        operations-per-run: 50
        stale-issue-label: status:stale
        stale-issue-message: 'This issue has been open for a while with no recent
          activity. If this issue is still important to you, please add a comment
          within the next 7 days to keep it open. Otherwise, the issue will be automatically
          closed to free up time for other tasks.


          Issues should be closed if:

          - They are duplicates of other issues

          - There is not enough demand

          - They are no longer relevant

          - There are not enough details

          '
        stale-pr-label: status:stale
        stale-pr-message: 'This pull request has been open for a while with no recent
          activity. If you''re still working on this or waiting for a review, please
          add a comment or commit within the next 7 days to keep it open. Otherwise,
          the pull request will be automatically closed to free up time for other
          tasks.


          Pull requests should be closed if:

          - They have been superseded by another pull request

          - They are out of scope or don''t align with the project

          - They have become obsolete due to other changes

          - They have bugs or conflicts that won''t be resolved

          '
name: Close stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  issues: write
  pull-requests: write
